name: Pages

on:
  push:
    branches:
      - gh-pages-release
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - run: npm ci
      - run: npm run export:gh-pages
      - run: |
          git add -A
          if ! git diff --cached --quiet
          then
            git config --global user.email "nekmeshi@gmail.com"
            git config --global user.name "nek0meshi"
            git rev-parse HEAD | xargs git commit -m $1
            git push origin HEAD:gh-pages -f
          fi
